# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
      with:
       node-version: '16'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: clock
      run: 
        python clock-2023-2-15.py
    - name: Commit
      run: |
        git config --global user.email 912828696@qq.com
        git config --global user.name yao
        git add .
        git commit -m"action:`date`"
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master

